### ISSUE TITLE
Add some way to control plugin initialization order

### ISSUE THREAD

**Issue by Katrix** [SpongePowered/SpongeAPI#1564] opened 2017-05-20 20:40 UTC
Up until now I've always believed that the dependency field in the `mcmod.info` file controlled in what order plugins are initialized. After talking to minecrell today I learned that what it actually controls is the classloading order. If a plugin is specified as a dependency, then it can be sure that the classes in the plugins in depends on are loaded (except with forge where it doesn't always work).

While I can understand that in many cases the initialization order between plugins don't matter, I still think it would be good to have a way to control in what order plugins are initialized in too. Forge for example has `requiredAfter`. 

You could argue that you can use a later init event, but as said in the sponge docs, most work should be finished at certain points, so why push everything to a later point instead?

At the very least I'd like for the JavaDoc to be changed to better reflect what's meant with loaded before. As it is at the moment, it not clear that it's talking about classloading.

**Comment by stephan-gh** [comment] 2017-05-21 09:49
Duplicate of https://github.com/SpongePowered/SpongeAPI/issues/1070, please comment there.

**Closed as completed by stephan-gh** 2017-05-21 09:49 UTC
Labels: resolution: duplicate
