### ISSUE TITLE
CommandSpec: Tab-completion for subcommand arguments

### ISSUE THREAD

**Issue by eitanmk** [SpongePowered/SpongeAPI#604] opened 2015-04-29 02:27 UTC
EDITED

Not sure if this is a bug or a feature request. (Also, I think this is the correct place to file this. Please forgive me if that's incorrect.)

The issue I'm having is the automatic tab-completion that is done when using the CommandSpec API. In my setup, I have a top level command that has three subcommands. The tab completion works for filling in the three subcommands as expected:

![top-level tab-completion working](https://s3.amazonaws.com/f.cl.ly/items/3g0g1s2o0m3P3e1D2N0C/Screen%20Shot%202015-04-28%20at%2010.13.29%20PM.png)

However, I'd like to set the arguments for subcommands. When I use the .setArguments() on a child CommandSpec, it seems to always just repeat the selected subcommand:

![subcommand tab-completion not working](https://s3.amazonaws.com/f.cl.ly/items/000p3M1P1T1d0p1p0e0Y/Screen%20Shot%202015-04-28%20at%2010.17.53%20PM.png)

This happens both for when I set the subcommand to accept no arguments using 'none()', and also with the 'choices()' call I'd like to use to autocomplete the available options.

EDIT: So actually, the completion DOES work for the subcommands if you start typing a valid option. So, I think the bug is that it completes the subcommand name when you don't type anything. The expected behavior would be to show the comma separated list of available completions and cycle through them on further Tab presses.

Here's the simplified code I'm using to build the commands:

```java
		HashMap<String, String> test = new HashMap<String, String>();
		test.put("moduleA", "moduleA");
		test.put("moduleB", "moduleB");

		this.subCommands.put(Arrays.asList("list"), CommandSpec.builder()
				.setDescription(Texts.of("List status of modules"))
				.setArguments(none())
				.setExecutor(new ListSubcommand())
				.build());

		this.subCommands.put(Arrays.asList("enable"), CommandSpec.builder()
				.setDescription(Texts.of("Enable specified module"))
				.setArguments(seq(choices(Texts.of("moduleName"), test)))
				.setExecutor(new EnableSubcommand())
				.build());

		this.subCommands.put(Arrays.asList("disable"), CommandSpec.builder()
				.setDescription(Texts.of("Disable specified module"))
				.setArguments(seq(choices(Texts.of("moduleName"), test)))
				.setExecutor(new DisableSubcommand())
				.build());

		this.cmdSpec = CommandSpec.builder()
				.setDescription(Texts.of("Manage modules"))
				.setExtendedDescription(Texts.of("List, enable/disable modules"))
				.setChildren(this.subCommands)
				.build();
```

System details:
Forge: 8.0.76.1397
Sponge: 1.8-1371-2.1DEV-433
Java: 1.8.0_20

I just switched to the latest dev build of Sponge to make sure the behavior was still present.

**Comment by eitanmk** [comment] 2015-04-29 03:44
Or, if there are too many options to suggest (such as listing online players, or a lot of keys in a choices map), can we print a message saying there are too many options and more context is needed?

**Comment by verbeto** [comment] 2015-05-01 10:51
To add on to this, when using the Cookbook example "WorldsTest" command /tpworld, the first parameter (a player) is correctly entered using tab complete however when tab is pressed again it switches to the next parameter (a world). It does this because the first argument has been correctly entered (player name) however we should only cycle the next parameter set (world list) if there is a space on the end of the tab list string. I probably didn't explain that too well, so here's an example:

/tpworld <press tab here> would give you a tab completion list of all players on the server. Perfect.

/tpworld GenericPlayer<press tab here> would switch tab completion list to all currently loaded worlds, which is not what we want to do. Although we have entered a parameter, if we press tab here we want to cycle the list of players, not the next parameter set- all currently loaded worlds.

/tpworld GenericPlayer <press tab here> would, as it should be, cycle all worlds.

**Comment by boformer** [comment] 2015-05-01 23:49
@verbeto So you mean ``"/tpworld GenericPlayer"`` vs. ``"/tpworld GenericPlayer "``

**Comment by verbeto** [comment] 2015-05-02 07:48
Somehow my [press tab here] parts decided to be removed, but it's fixed now.
@boformer

**Comment by gabizou** [comment] 2015-05-21 05:33
@zml2008 Can this be fixed soon?

**Comment by zml2008** [comment] 2015-05-21 21:48
Ok, the issue here seems to be an ambiguity in what having another argument means. Currently, the argument parsing code trims spaces off of the ends of commands, which means that a user wanting to complete their current argument and a user wanting completions for the beginning of the next argument both appear the same to the commands system. I need to think about how to expose this to the argument parsing code. Maybe adding a hasTrailingSpace() method to CommandArguments, or an empty last argument? neither seem super great to me

**Comment by ryantheleach** [comment] 2015-05-22 01:14
Empty last argument seems to be most logical?

Spaces delimit arguments, and there is a space at the end, but does this screw with the parsing at all?

**Comment by zml2008** [comment] 2015-05-22 03:30
Well, in a lot of argument parsers empty arguments are stripped -- so unless the spaces are explicitly escaped one space is the same as 50 to the final argument parser. However, the end of the string is kind of a special case :/

**Comment by gabizou** [comment] 2015-12-06 23:34
Seeing that this issue is quite old, can anyone re-test this issue to see if it's still an issue?

**Comment by Aaron1011** [comment] 2015-12-12 14:08
@gabizou @zml2008 : I've confirmed this on the latest SpongeForge.

**Comment by TBlueF** [comment] 2015-12-21 15:12
Anything like the `hasTrailingSpace()` method would also be needed in the `TabCompleteCommandEvent` to detect the space between `getCommand()` and `getArguments()`.
See [this forum post](https://forums.spongepowered.org/t/tabcompletecommandevent-question/10342).

**Comment by zml2008** [comment] 2015-12-22 01:25
No, that would be the difference between getArguments being {""} and {} (1-element array of empty string vs 0-element array) -- which shouldn't be difficult to implement (besides String.split being dumb)

**Comment by TBlueF** [comment] 2015-12-22 01:40
@zml2008 Am i missing something? As far as i see [getArguments()](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/command/TabCompleteCommandEvent.java#L55) currently returns all arguments in one String on this event and not an Array?

**Comment by zml2008** [comment] 2015-12-22 01:42
hm, then might have to make it an Optional

**Closed** 2016-03-08 00:10 UTC
Labels: accepted, bug, commands, high priority
