### ISSUE TITLE
Expose Player flight and 'walk speed'

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#811] opened 2015-08-16 01:07 UTC
The [player abilities packet](http://wiki.vg/Protocol#Player_Abilities) contains two values that are normally let to their defaults - flight speed, and movement speed.

I haven't determined the unit on flight speed, but it affects both normal flying and ascent/descent with holding jump/sneaking. This is the only way to modify the ascent descent speed, as the movement speed attribute modifier doesn't affect it.

The 'walk speed' doesn't actually affect the client's walk speed at all - however, it does affect the FOV, after being combined with the movement speed attribute modifier (see `AbstractClientPlayer#getFovModifier).

I think both of these values, especially the flying speed, would be useful for plugins. The former could possibly be added as part of `FlyingData`. I'm not entirely sure about the 'walking speed', though I still think it might be useful.

**Comment by simon816** [comment] 2015-08-16 01:30
Related: #575

**Comment by gabizou** [comment] 2015-08-17 18:52
Closing as it's a duplicate of #575.

**Closed by gabizou** 2015-08-17 18:52 UTC
Labels: accepted, data
