### ISSUE TITLE
Command-Arguments prevent "No values matching..."-error-message of sub-commands 

### ISSUE THREAD

**Issue by Tr4p** [SpongePowered/SpongeAPI#2013] opened 2019-06-06 18:39 UTC
My goal was build my plugin commands like this:

`/myCommand <player>`
`/myCommand subCommand <player>`

In code this would be something like this:
```
CommandSpec subCommand = CommandSpec.builder()
	.arguments(GenericArguments.onlyOne(GenericArguments.player(Text.of("player"))))
	.executor(new SubCommand())
	.build();

CommandSpec mainCommand = CommandSpec.builder()
	.child(subCommand, "subCommand")
	.arguments(GenericArguments.optional(GenericArguments.onlyOne(GenericArguments.player(Text.of("player")))))
	.executor(new Command())
	.build();

Sponge.getCommandManager().register(this, mainCommand, "myCommand");
```

Which works and can be executed if all entered argument are valid.
But if you use some invalid argument you'll get an unexpected message.
For example if you executed `/myCommand subCommand notExistingPlayer`:
You' ll recieve: 
> Too many arguments!
> subCommand notExistingPlayer
> ^

Instead of: 
> No values matching pattern 'notExistingPlayer' present for player!
> subCommand notExistingPlayer
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^

This is the message i would expect. It's also getting recieved if there are no command-arguments allowed or set for the main command.

If you use the main command with some invalid input the message works like expected.
For example if you executed `/myCommand notExistingPlayer`:
You' ll recieve: 
> No values matching pattern 'notExistingPlayer' present for player!
> notExistingPlayer
> ^

**Comment by dualspiral** [comment] 2019-06-06 18:50
You need to set `childArgumentParseExceptionFallback` to `true` for the behaviour your describe - [Javadocs here](https://jd.spongepowered.org/7.1.0/org/spongepowered/api/command/spec/CommandSpec.Builder.html#childArgumentParseExceptionFallback-boolean-). Note that in this case, if you have a player named `subCommand`, you would not be able to select them as the subcommand would take precedence. It is a known limitation with the command system, one not really solvable in the current iteration (API 8 for 1.14 will have a different system to try to integrate with some of the features in 1.14)

See https://github.com/SpongePowered/SpongeAPI/issues/1647#issuecomment-330158258 for why this happens. Nothing more we can do within the confines of API 7.x, unfortunately.

Closing this as it's effectively a duplicate of #1647, as well as others.

**Closed as completed by dualspiral** 2019-06-06 18:50 UTC

**Comment by Tr4p** [comment] 2019-06-06 19:43
@dualspiral Thanks for the fast response. With the usage of `childArgumentParseExceptionFallback ` it works like expected. :)
