### ISSUE TITLE
API-8 TransactionTypes.VALUE and unit testing

### ISSUE THREAD

**Issue by ericgrandt** [SpongePowered/SpongeAPI#2336] opened 2021-04-25 16:14 UTC
I've recently been porting Total Economy over to API 8 and came to a bit of a blocker while using the TransactionTypes.DEPOSIT and its equivalents. It looks like those constants now require [Sponge to be initialized ](https://github.com/SpongePowered/SpongeAPI/blob/e15895954d43945f86fe6f8fbb3c29a15e031bfd/src/main/java/org/spongepowered/api/service/economy/transaction/TransactionTypes.java#L67) which makes it difficult to test. My current workaround is to completely avoid using those TransactionTypes in my Transaction/Transfer results which is not ideal. Is there a better way to do this where I can still use the transaction type and make testing possible?

Example of current JUnit test in Total Economy with workaround: https://github.com/Erigitic/TotalEconomy/blob/e89115c2c298b3b91f1185c97848b87996096e81/src/test/java/com/erigitic/domain/TEAccountTest.java#L103-L120

**Comment by dualspiral** [comment] 2021-04-25 17:00
(This isn't actually an apprpropriate question for Github Issues as it's not a bug nor a feature request. I am going to close this, but I do have a semi-answer for you anyway. Questions like this are better on the forums or on Discord in #plugins).

In theory, you can do it now, but I say so knowing that it's somewhat... complex to do.

Remember that we allow for injecting a `Game` into your plugin which is an interface which you can pass around to appropriate places. You can use that to get the appropriate registry and create appropriate resource keys, get the factory to get the resource keys and mock them 'till your heart's content. You could absolutely do it that way... but it'll be a pain in the ass.

A better way is to use a bit of creative thinking and abstract accessing keys/types behind your own interface, which you can mock in your unit tests and forward calls to the Sponge objects in your actual plugin - something like.

```java
public interface TransationTypeProvider {

    TransactionType deposit();

    TransactionType withdraw();

}
```

where you create an implementation during plugin init that returns the fields in Sponge, and in unit testing it creates an alternative implementation that returns mocked types. It forces you to pass this object to the correct places, but it does make things more testable.

It's up to you to find a way that supports your plugin - there are plenty of ways to do it, but at its core, this isn't Sponge related, more to do with how you structure your own code.

**Closed as completed by dualspiral** 2021-04-25 17:00 UTC

**Comment by gabizou** [comment] 2021-04-25 17:14
Something something sponge api mocking library. Would be cool, maybe to go along with a tool chain we eventually build to replace mctester.
