### ISSUE TITLE
Add Value API overloaded method for itemData() in ItemStack.Builder

### ISSUE THREAD

**Issue by DotDashh** [SpongePowered/SpongeAPI#1096] opened 2016-02-23 02:12 UTC
Pretty much summed up in the title.

If not, I am requesting that there be such method in ItemStack.Builder:
`itemData(Keys<? extends BaseValue<E>> key, E value)`

That way it is easier to add say enchantments in one fell swoop.

**Comment by gabizou** [comment] 2016-02-23 03:52
Duplicate of https://github.com/SpongePowered/SpongeAPI/issues/1093

**Closed by gabizou** 2016-02-23 03:52 UTC
Labels: duplicate
