### ISSUE TITLE
SpongeForge 1.12.2 rcon error

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/SpongeAPI#1672] opened 2017-10-25 12:23 UTC
[15:15:42] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
[15:15:42] [RCON Client #3/ERROR]: Exception whilst parsing RCON input
java.lang.IllegalStateException: CauseStackManager called from off main thread!
        at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:70) ~[SpongeCauseStackManager.class:1.12.2-2503-7.0.0-BETA-2706]
        at org.spongepowered.common.event.SpongeCauseStackManager.pushCause(SpongeCauseStackManager.java:98) ~[SpongeCauseStackManager.class:1.12.2-2503-7.0.0-BETA-2706]
        at net.minecraft.network.rcon.RConThreadClient.handler$rconLoginCallback$znd000(SourceFile:599) ~[qb.class:?]
        at net.minecraft.network.rcon.RConThreadClient.run(SourceFile:70) [qb.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[15:15:42] [RCON Client #3/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: CauseStackManager called from off main thread!
[15:15:42] [RCON Client #3/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:70)
[15:15:42] [RCON Client #3/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at org.spongepowered.common.event.SpongeCauseStackManager.pushCause(SpongeCauseStackManager.java:98)
[15:15:42] [RCON Client #3/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at net.minecraft.network.rcon.RConThreadClient.handler$rconLogoutCallback$znd000(SourceFile:616)
[15:15:42] [RCON Client #3/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at net.minecraft.network.rcon.RConThreadClient.func_72653_g(SourceFile)
[15:15:42] [RCON Client #3/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at net.minecraft.network.rcon.RConThreadClient.run(SourceFile:97)
[15:15:42] [RCON Client #3/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at java.lang.Thread.run(Thread.java:748)
[15:17:23] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
[15:17:23] [RCON Client #4/ERROR]: Exception whilst parsing RCON input
java.lang.IllegalStateException: CauseStackManager called from off main thread!
        at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:70) ~[SpongeCauseStackManager.class:1.12.2-2503-7.0.0-BETA-2706]
        at org.spongepowered.common.event.SpongeCauseStackManager.pushCause(SpongeCauseStackManager.java:98) ~[SpongeCauseStackManager.class:1.12.2-2503-7.0.0-BETA-2706]
        at net.minecraft.network.rcon.RConThreadClient.handler$rconLoginCallback$znd000(SourceFile:599) ~[qb.class:?]
        at net.minecraft.network.rcon.RConThreadClient.run(SourceFile:70) [qb.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[15:17:23] [RCON Client #4/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: CauseStackManager called from off main thread!
[15:17:23] [RCON Client #4/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:70)
[15:17:23] [RCON Client #4/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at org.spongepowered.common.event.SpongeCauseStackManager.pushCause(SpongeCauseStackManager.java:98)
[15:17:23] [RCON Client #4/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at net.minecraft.network.rcon.RConThreadClient.handler$rconLogoutCallback$znd000(SourceFile:616)
[15:17:23] [RCON Client #4/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at net.minecraft.network.rcon.RConThreadClient.func_72653_g(SourceFile)
[15:17:23] [RCON Client #4/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at net.minecraft.network.rcon.RConThreadClient.run(SourceFile:97)
[15:17:23] [RCON Client #4/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at java.lang.Thread.run(Thread.java:748)

**Comment by Cybermaxke** [comment] 2017-10-25 12:24
https://github.com/SpongePowered/SpongeCommon/issues/1533
https://github.com/SpongePowered/SpongeCommon/pull/1526

**Comment by kashike** [comment] 2017-10-25 16:08
duplicate of https://github.com/SpongePowered/SpongeCommon/issues/1533

**Closed as completed** 2017-10-25 16:08 UTC
Labels: resolution: duplicate
