### ISSUE TITLE
Using setLocation() and transferToWorld() in MoveEntityEvent.Teleport.Portal causing issues

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeAPI#1568] opened 2017-06-01 09:39 UTC
I'm trying to teleport the player to a different dimension if he enters the nether portal. For that I'm using and canceling the `MoveEntityEvent.Teleport.Portal` event.
The issue is that if I use `setLocation()` or `transferToWorld()` in that event it will bug out (chunks not loading, /getpos still shows the previous world (nucleus command)) until the player reconnects.

**Comment by ryantheleach** [comment] 2017-06-02 00:27
Are you cancelling it or modifying it? I don't understand how doing both is useful?

My understanding is:

Cancelling the event should cancel the teleport, you stay in the same world as you left.

Transferring someone to a world after cancelling should throw a teleport event again, with a plugin cause.

Modifying the transforms in the event, would normally change the location you are heading to, but since it's a portal event, I'm not sure how that potentially conflicts with the portal agent.

What you might need to do, is create a custom portal agent and supply that, depending on your exact usecase.

https://github.com/SpongePowered/SpongeAPI/blob/a4aaeec0007ebd9c3570e41382454e81f875e0a1/src/main/java/org/spongepowered/api/world/PortalAgent.java

In addition, unless this is a design issue of the API, what you are experiencing sounds like a SpongeForge / SpongeVanilla / Sponge Common implementation issue.

Try testing on SF / SV and report the versions used and what happens. if it disagree's to the javadocs / API report a bug on SF/SV/SC.

If someone attempting to implement / use the API finds it unworkable, then they can ***then*** create an issue against the API.

**Comment by Sir-Will** [comment] 2017-06-02 02:34
Canceling. Instead of teleporting the player to the nether and creating an portal in that dimension I want to teleport the player to a world spawn of a different world.
That's how it basically looks:
```java
@Listener
public void onPlayerTeleport(MoveEntityEvent.Teleport.Portal event, @Getter("getTargetEntity") Player player) {
    event.setCancelled(true);
    player.transferToWorld(Sponge.getServer().getWorld("DIM6").get());
}
```

If I only change the location with `setToTransform()` it will probably create a nether portal in that world or am I wrong?

**Comment by ryantheleach** [comment] 2017-06-02 04:11
SpongeCommon shouldn't be bugging out with the code you have shown. it's an implementation bug I think.

@trentech have you come across anything like this?

" creating an portal in that dimension "
For cleaner code / giving the server admins more control I'd suggest using a portal agent. The portal agent to be used can be configured in the server settings.

> 
>  * An agent that handles teleportation between {link Location}'s. This can be
>  * understood as an agent that handles the creation of "portals" between
>  * {link World}'s.
>  *
>  * <p>An example is the agent handling nether portals.</p>

**Comment by Sir-Will** [comment] 2017-06-02 04:48
Create an issue in SpongeCommon.
> creation of "portals"

Hm, I don't want to create any portal only teleport the player.
How I already tried it is the best way to do that I think.

**Comment by dualspiral** [comment] 2017-06-02 07:19
> Transferring someone to a world after cancelling should throw a teleport event again, with a plugin cause.

Just to point out, he's not doing it after - he's transferring someone _during_ the event's lifecycle. The portal event handling code still has to fire - he'll raise an event whilst another teleport event is still in progress (even though it's cancelled), in theory, this could be uncancelled later too. I've not looked into the code that does this, and maybe there is an implementation bug that could be squashed, but using `setTransform` during an event that is intended to change your location is possibly undefined - he's calling code to teleport someone within another teleport event. 

I suggest using a scheduler to work around this, schedule the location change for straight away which should run the task at the next oppotunity, taking `setTransform` out of this event.

> If I only change the location with setToTransform() it will probably create a nether portal in that world or am I wrong?

Try it. It shouldn't take long, probably less time than waiting for an answer here.

**Comment by ryantheleach** [comment] 2017-06-02 07:43
>Just to point out, he's not doing it after - he's transferring someone during the event's lifecycle. The portal event handling code still has to fire - he'll raise an event whilst another teleport event is still in progress (even though it's cancelled), in theory, this could be uncancelled later too. 

I've always known where in the code the events get thrown, but that's the first time that I've thought of it this way conceptually from a plugin POV. Now the trick of firing stuff on the next tick doesn't seem like as much of a hack as I previously thought it was, and understand some of the reasoning behind Sk89q's callback proposal.

This is really something that should be covered in some depth somewhere, in order to help people who have only really seen the API side of things.

**Comment by Sir-Will** [comment] 2017-06-02 09:53
Just tested `setToTransform()` and it creates an portal. Seems to even create a end portal if you change the location to the end.

**Comment by Sir-Will** [comment] 2017-06-02 10:31
Ok, using a delay prevents this issue.

**Comment by dualspiral** [comment] 2017-06-02 10:34
I think the solution is to update the documentation on any `MoveEntityEvent` events to note that any changes to the player position must be done via the event `setToTransform` method. Maybe an API method is also needed on the portal event to prevents the creation of a portal. Don't know what anyone else thinks, though.

**Comment by ryantheleach** [comment] 2017-06-02 15:12
>prevents the creation of a portal

In my mind, if you are transferring between worlds and want to override the portal creation behavior, that's exactly what portalagents are designed and exposed for.

Otherwise if a method to the event is added, custom portal agents need to respect the result, and I'm not sure how hairy that gets, maybe the implementation could never call the create/find portal methods though...

**Comment by Sir-Will** [comment] 2017-06-04 09:06
Found another weird issue with this.
Doing `player.getLocation()` before `event.setCancelled(true);` will give you the coordinates of the destination (nether) but the world of the start position (overworld, where I entered the portal).

How can I get the start/enter location when I don't cancel the event?

**Comment by dualspiral** [comment] 2017-06-04 09:36
Report that to Sponge Common.

**Comment by Zidane** [comment] 2017-10-11 15:51
Closing this issue as  the original intent of the issue is to use the scheduler and blood already fixed cancelling the portal event still creating the portal blocks in bleeding.

If we have other problems, create new issues on SpongeCommon as @dualspiral  said.

**Closed as completed by Zidane** 2017-10-11 15:51 UTC
