### ISSUE TITLE
Get current world time/moon phase

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#1623] opened 2017-08-05 12:00 UTC
Seems like we cannot get/or set current world time, nor phase of the moon.

**Comment by gabizou** [comment] 2017-08-05 21:03
Duplicate of https://github.com/SpongePowered/SpongeAPI/issues/393

**Closed as completed by gabizou** 2017-08-05 21:03 UTC
Labels: resolution: duplicate

**Comment by parlough** [comment] 2017-08-17 05:03
Also I would like to note you can currently get and set world time through the `WorldProperties` class. So you could do `world.getProperties().setWorldTime(500)`.
