### ISSUE TITLE
ItemStack data loss unserialize

### ISSUE THREAD

**Issue by SimonBHB** [SpongePowered/SpongeAPI#2044] opened 2019-09-01 11:32 UTC
Bonjour, quand je déserialize un ItemStack je perds mes key comme si elles étaient ignoré.

translate.google.fr:
Hello, when I deserialize an ItemStack I lose my key as if they were ignored.

----
Use ExampleDataPlugin: https://github.com/pie-flavor/ExampleDataPlugin

My code:
MyImmutableInventoryData: https://pastebin.com/UbZGGhFD
MyInventoryData: https://pastebin.com/1JeLmciS
MyInventoryDataBuilder: https://pastebin.com/u6SAg5vb

Register<Key<?>/GamePreInitializationEvent : https://pastebin.com/k9WUwRYJ
code serialize/unserialize: https://pastebin.com/tKRNiqTX

----

json conf: https://pastebin.com/NJpB4Rfc
toContainer serialize: https://pastebin.com/2vJ3HLPf
toContainer unserialize: https://pastebin.com/K28jzUGc

**Comment by ImMorpheus** [comment] 2019-09-13 16:40
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/2378

and wrong repo. (I know this was older, but I'm keeping the other one to avoid closing and moving).

**Closed as completed by ImMorpheus** 2019-09-13 16:40 UTC
Labels: resolution: duplicate, resolution: moved
