### ISSUE TITLE
Portal API?

### ISSUE THREAD

**Issue by KieronWiltshire** [SpongePowered/SpongeAPI#611] opened 2015-04-30 17:50 UTC
So I've looked into the API, but I've struggled to find if it's possible to create custom 'sub' worlds so to speak.

So for instance, imagine a plug-in which handles the generation of a different type world. The plug-in would also allow players to create their custom portals to access these custom worlds worlds, similar to how players can create Nether portals to access the Nether.

What I essentially would like to do, is be able to store this world as a 'sub' world so to speak, similar to how the Nether and End dimensions work.

I think this would be extremely useful.

**Comment by Zidane** [comment] 2015-05-01 03:25
@KieronWiltshire 
We want to write a portal API, just haven't gotten to it yet.

**Comment by gabizou** [comment] 2015-05-01 06:28
Closing as it's a duplicate of #504

**Closed by gabizou** 2015-05-01 06:28 UTC
Labels: enhancement, help wanted

**Comment by KieronWiltshire** [comment] 2015-05-01 12:38
@gabizou how is this a duplicate? I'm taking about the ability to have separate worlds treated as dimensions or 'sub worlds' like the Nether and End, so they fall under the same directory as the 'overworld'.

**Comment by Mumfrey** [comment] 2015-05-01 12:45
@KieronWiltshire it's a duplicate because the structure of the worlds is pretty much irrelevant. Once you have a portal API you're basically free to do what you want with them.

**Comment by KieronWiltshire** [comment] 2015-05-01 13:12
@mumfrey the structure wouldn't be irrelevant, i'd prefer it if I didn't have 'world' and 'world_skylands' like bukkit did, it's terrible.

**Comment by Mumfrey** [comment] 2015-05-01 13:30
That doesn't really have anything to do with portals though, and it's definitely not an API issue.

As you can see from the current *implementations* the worlds created are simply dimensions under the main world save folder, though any implementation is free to make whatever decision it wishes about how world data are serialised. So yes, the structure *is* irrelevant from an API perspective.
