### ISSUE TITLE
Replace Optional<X> with Optional<? extends X>

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/SpongeAPI#369] opened 2015-01-04 22:13 UTC
I encountered a little problem while looking at the Sponge Implementation and extending existing events.

**The issue**
I can overwrite every method to return a more precise result than the base interface specifies. However using the Optional destroys that benefit if used the way we currerntly do.

Here is an example code
````java
public interface Test {

    Optional<Test> getSelf();

    Optional<? extends Test> getBetterSelf();

}
````
and the second file
````java
public class Proof implements Test {

    @Override
    // public Optional<Proof> getSelf() { - NOT POSSIBLE
    public Optional<Test> getSelf() {
        // return Optional.of(this); - NOT POSSIBLE
        return Optional.of((Test) this);
    }

    @Override
    public Optional<? extends Proof> getBetterSelf() {
        return Optional.of(this);
    }
    
    public void foo() {
        Proof self = getBetterSelf().get();
        // Proof self2 = test.getSelf().get(); - NOT POSSIBLE
        Proof self2 = (Proof) test.getSelf().get();
    }

}
````
Image the Sponge server itself has  a specific subclass for one of its events, which uses a subclass of the original class/interface because a method was added that is required for further use. So if you listen to the given event and you try to get it, you will actually get the base interface because you have to downcast it, but if you use the `<? extends T>` for example this is no longer an issue you class can simply overwrite the return type and everything will be fine.

If we change it we have basically three benefits:
* Avoid unnecessary casting while creating the `Optional`
* Avoid unnecessary casting while getting the `Optional`'s value
* Allow other APIs to extend our API more safely and freely.

I suggest replacing/changing it in the entire API (where the Optional references a class within the  `org.spongepowered.api.**` package) , i also offer my help to change it.
This would also include immutable `Iterable`s, `Collection`s, ...., `Map`s.

**Comment by Minecrell** [comment] 2015-01-04 22:32
I can confirm this is a problem for some parts of the API, but we need to check where having more precise results are really need it. I had to use it in #367 in order to be able to override the return value in `StatusPingEvent` for a method with `Optional`. https://github.com/SpongePowered/SpongeAPI/pull/367/files#diff-70bb07711fbf5aabad54031ef7fd11aaR59

**Comment by ST-DDT** [comment] 2015-01-04 22:47
IMO it is need everywhere or at least useful everywhere.
Think of CopyPasting the entire API and just replace all interfaces with implementations, including those in the optionals. 
In some cases you may not be able to declare the extended optionals (events with setters) but in that cases it does not hurt either, does it?

**Comment by Minecrell** [comment] 2015-01-04 23:02
I don't think you'll want (nor would it make sense) to have something like `Optional<? extends String>` or `Optional<? extends Integer>`. ;)

**Comment by ST-DDT** [comment] 2015-01-04 23:07
@Minecrell Thats true. So everywhere is not entirely true.
With everywhere i actually meant that i would use a regex to search for occurrences and then replace it on the fly if necessary. Basically all places that use a class with `org.spongepowered.api..*` as package for the optional type.

**Comment by Minecrell** [comment] 2015-01-04 23:21
It wouldn't be possible to use this in the SpongeGameRegistry methods. The cast in https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/registry/SpongeGameRegistry.java#L200 couldn't be prevented using this because the internal instances of Minecraft will only be patched with the mixins at runtime (AFAIK), therefore you couldn't return a more precise value there, the compiler will say that they don't extend the Sponge interfaces. So they wouldn't match `Optional<? extends ItemType> at compile time.

**Comment by ST-DDT** [comment] 2015-01-05 07:02
You are right once again.
But there are things in the Impl that will benefit from it. All those with a map in that class. In the other cases there will/may already be other server implementations that will bemefit from it.

**Comment by ST-DDT** [comment] 2015-01-06 19:40
@Minecrell Shall i start working on it or is this something for the team to do?
Notice: This would be a huge change, because it also affects Iterable/Collection/Set/List.

**Comment by Minecrell** [comment] 2015-01-06 19:53
@ST-DDT We need some more discussion on this first.
@SpongePowered/developers Any other opinions on this?

**Comment by modwizcode** [comment] 2015-01-06 20:21
I'm not sure I understand the issue, can someone explain it more clearly?

**Comment by modwizcode** [comment] 2015-01-07 04:17
I somewhat prefer not having this mainly because its so incredibly long
with optional returns as it is. Using an additional <? extends X> is extra
long compared to a plain <X>. However unless I misunderstand something,
internally Java does not know that <? extends X> is really a <Y> so it
won't actually solve this problem anyway.

Correct me if I am wrong there. If so an explanation of what's wrong with
that interpretation would be appreciated.

**Comment by kenzierocks** [comment] 2015-01-07 04:18
@modwizcode The point is not to make Java think that `Optional<? extends X>` is a `Optional<Y>`, but rather so we can *specify* that in subclasses of Events (Sponge implementations) and avoid casts that are dangerous.

**Comment by modwizcode** [comment] 2015-01-07 04:20
Ah I misunderstood the meaning of X. I'm in favor of this for the most
part. Although it seems like variable definitions will be kind of long.
Which is something I already dislike about Optionals.

**Comment by kenzierocks** [comment] 2015-01-07 04:36
Let's compare an example I wrote up from the API.

[`Cause.java`](https://github.com/SpongePowered/SpongeAPI/blob/eadbd1e819141228a9528ca826681288e70a3ca9/src/main/java/org/spongepowered/api/event/cause/Cause.java) has `Optional<Cause> getParent()`:
```
    public Optional<Cause> getParent() {
        return parent;
    }
```

We now subclass Cause into `PlayerCause` (example, class does not exist) which wants to return itself as the parent cause (for some unknown reason, this is a bad example), but we can't change the return value!

PlayerCause.java
```
    @Override
    public Optional<PlayerCause> getParent() { // does not compile ;(
        return parent;
    }
```

Now, with a revised `Cause.java`:
```
    public Optional<? extends Cause> getParent() {
        return parent;
    }
```

Here's
`PlayerCause.java`
```
    @Override
    public Optional<? extends PlayerCause> getParent() {
        return parent;
    }
```

No problems! Yay!

**Comment by DarkStorm652** [comment] 2015-01-13 02:20
(Clarifying the issue here:) Java's generics require covariance to be specified upon usage of a type in the form of `? extends T`, providing no mechanism for specifying covariance upon declaration of a type such as Scala's `class A[+T]`. With covariance, a type A<X> is a subtype of A<Y> if X extends Y.

Whereas the default behavior for an overrided method in Java is to allow returning of subtypes of the overrided method's original return type, generics does not default to such behavior for a parameterized type (Optional<X> is not a subtype of Optional<Y> even if X extends Y) and thus has to be manually specified via Optional<? extends X>. All you are really doing by specifying Optional<? extends X> is bringing back the normal behavior for return types -- and although it may be verbose, covariance will most likely be what Java developers will be expecting to be able to do. (Principle of Least Astonishment! Decrease the frustration!)

**Comment by Axiometry** [comment] 2015-01-13 02:30
(Clarifying the issue here:) Java's generics require covariance to be specified upon usage of a type in the form of `? extends T`, providing no mechanism for specifying covariance upon declaration of a type such as Scala's `class A[+T]`. With covariance, a type `A<X>` is a subtype of `A<Y>` if `X` extends `Y`.

Whereas the default behavior for an overrided method in Java is to allow returning of subtypes of the overrided method's original return type, generics does not default to such behavior for a parameterized type (`Optional<X>` is not a subtype of `Optional<Y>` even if `X` extends `Y`) and thus has to be manually specified via `Optional<? extends X>`. All you are really doing by specifying `Optional<? extends X>` is bringing back the normal behavior for return types -- and although it may be verbose, covariance will most likely be what Java developers will be expecting to be able to do. (Principle of Least Astonishment! Decrease the frustration!)

I support this completely as an advocate of user-friendly API design :stuck_out_tongue:

And to use the example of `Optional<? extends String>`, isn't this how normal method return types work? If I have the class
```java
abstract class IHaveAStringReturnTypeHahaha {
  public String getMyString();
}
```
If I were to somehow extend `String` with my own class (in this example, `UltimateHackerString`), I could just as well do
```java
class IHackedYourStringReturnTypeHuehuehue extends IHaveAStringReturnTypeHahaha {
  @Override
  public UltimateHackerString getMyString();
}
```
Which shows that it is fine to replace ALL the `Option<X>`s with `Option<? extends X>`s, though a bit excessive.

**Comment by ST-DDT** [comment] 2015-01-13 18:33
I added an example PR which should show the required changes for the API.

**Comment by Minecrell** [comment] 2015-01-22 14:39
Closing this for the reasons mentioned in #386.

**Closed by Minecrell** 2015-01-22 14:39 UTC
Labels: input wanted
