### ISSUE TITLE
Ensure resetting the state of CommandArgs reverts and inserted/removed arguments

### ISSUE THREAD

**Issue by SimonFlash** [SpongePowered/SpongeAPI#1867] opened 2018-07-19 05:28 UTC
*related to [SpongeCommon#2006](https://github.com/SpongePowered/SpongeCommon/issues/2006)*

The state of `CommandArgs` does not include the current list of arguments, so when setting the state any inserted or removed arguments from parsing will remain. The most notable example of this in use is with [CommandFlags](https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/command/args/CommandFlags.java#L83), where parsed flags are removed so that they can be declared anywhere in the command. See [SpongeCommon#2006](https://github.com/SpongePowered/SpongeCommon/issues/2006) for issues that can result from this.

A workable solution for the meantime is to add a package-private `setArgs` method onto CommandArgs (as there is already a `getArgs` method as well). This can then be added to things like `GenericArguments#firstParsing` where needed on a case-by-case basis. Longer term, I believe that the object returned by `getState` needs to be updated to include this information. Alternatively, a snapshot system could be put in place, and this should supersede the use of `getState`/`setState`.

**Comment by dualspiral** [comment] 2018-07-19 12:41
> Alternatively, a snapshot system could be put in place, and this should supersede the use of getState/setState

That's the better option and is the one I would rather pursue.

As `getState/setState` return/use `Object`, I could just update those. However, as the impl is part of the API, I'm wary about changing the current impl from an integer to a snapshot because there will be someone, somewhere that relies on that. 

Basically:

* If we consider that the API is simply based on the intention of the signatures, we just update `getState/setState` to return snapshots, and breakages are down to users assuming something about the internals that they shouldn't be assuming. This is the safest option in terms of keeping the args consistent, `get/setState` are designed to not make any guarantees other than restoring the state of the command.
* If we consider that the API is not just the signatures but the contents of the methods, then we just add the snapshot methods and make sure the get/set state methods are deprecated. This is the safest from a plugin "breakages" point of view if they make the assumption that the returned object is an integer - though I suppose there is the possibility that having two state restoring methods could cause some havoc.

I would much rather the former as we won't be making any ABI/API breaks, but I'm leaning towards the latter as a safer option for existing plugins, and should have no problems as long as elements that others write don't call into other elements that might change the arg list - but that was always a problem anyway, it might just change the assumptions of others (and I don't think it'll be a large issue).

@gabizou @Zidane have you any thoughts on the above and what we want to define as the public API in this scenario? I believe using `Object` was intended to prevent breaks in the same major version, but I'm wary about the wider picture. 

I'll try to get a PR in later today to show what I'm thinking.

**Comment by ryantheleach** [comment] 2018-07-19 14:21
Talking to zml when I made some early PR's to commands leads me to believe that's ENTIRELY the reason why it was an object return type.

It's an implementation specific memento.

**Comment by dualspiral** [comment] 2018-07-19 14:29
I get that, it was the impression I got too. However, just because that's the _intention_ doesn't mean it matches with reality. The question I'm asking is whether we regard the API (that is, what is regarded as the guaranteed behaviour) as only the signatures, or the contents of anything implemented in there - if it's the latter, then it doesn't matter that the signature is based on the "Object" type, the entire implementation could be considered a contract and barring any issues with the implementation in the API itself, it should not be touched/changed.

That's why I'm asking for clarification. I am not making this decision on my own, regardless of intention.

**Comment by gabizou** [comment] 2018-07-19 17:05
I'm putting my vote for:
>If we consider that the API is simply based on the intention of the signatures, we just update getState/setState to return snapshots, and breakages are down to users assuming something about the internals that they shouldn't be assuming. This is the safest option in terms of keeping the args consistent, get/setState are designed to not make any guarantees other than restoring the state of the command.

I personally believe in not abusing vague ambiguity with this where plugins can presume to have an object other than an int for state. I'd rather we actually correct this and for the eventual break of commands in 1.13, we don't have to worry about remembering to remove broken stuff that we patched to fix correctly.

**Comment by dualspiral** [comment] 2018-07-19 17:08
I’m happy with that. This will be incoming within the hour.

**Closed as completed** 2018-07-19 17:56 UTC
Labels: system: command
