### ISSUE TITLE
Add an event for block break start , end and abort

### ISSUE THREAD

**Issue by jd1378** [SpongePowered/SpongeAPI#1778] opened 2018-02-10 23:23 UTC
what i tried was InteractBlockEvent.Primary.MainHand , which is getting fired on every tick (i guess) when mining the block , so its not possible to get when the player started digging without listening for the packet . 
adding this will be nice

**Comment by ryantheleach** [comment] 2018-02-11 06:58
@jd1378 What is your usecase?

Some use cases I can think of off the top of my head that may or may not want to be considered.

1. Anticheat plugin that needs to log/know everything to make smart decisions, usually monitor only.
2. A plugin that wants to cancel / create / manipulate the block breaking effects.
3. A plugin that wants to warn a player as early as possible about protected areas, but doesn't want to spam their chat every tick.
4. A plugin that want's to time how long it takes to break blocks?
5. A plugin that wants to manipulate how long it takes to break a block.

**Comment by RedNesto** [comment] 2018-02-11 13:07
Where should be the event? In `ChangeBlockEvent.Break`? like `ChangeBlockEvent.Break.Start`/`Stop`/`Abort` ?

**Comment by jd1378** [comment] 2018-02-11 23:20
@ryantheleach 1 and 4 are my usecase,
@RedNesto I don't know exactly where the event should be in the API, but IMO it is not necessarily changing the block , while its related to changing the block ,but anyway, what you suggest seems fine to me

**Comment by ryantheleach** [comment] 2018-02-12 00:49
It won't be ChangeBlockEvent as the block isn't being changed until it finally breaks.

**Comment by jd1378** [comment] 2018-02-12 05:41
Since there is Key for Sneaking and Sprinting , why not add the key for these ?
Or there can be a new PlayerActionEvent with both entity action and player digging ?  `PlayerActionEvent.Start.Sneaking`/`Sprinting`/`Mining`....?

**Comment by RedNesto** [comment] 2018-02-12 06:49
The `Player` part of the event name can be too restrictive, so I'll ask here what I asked you in PM: Can Humans/Humanoids dig?

The another issue with the event you are giving us is that the last sub-events (`Sneaking`, `Sprinting`) are already accessible via the Keys so what about just a `DiggingBlockEvent` with sub-event like `Start`/`Stop`/`Abort`?

**Comment by gabizou** [comment] 2018-02-12 09:44
I'd keep it named as `Action` `Target` `Event` as the API follows, like `ChangeBlockEvent` or `DestroyLivingEvent`, etc. Since the action is always constant, the target can change, and we don't use the source in the naming convention since it is included already in the cause.

I'm in favor of `DiggingBlockEvent` with `Start` / `Stop` / `Abort` and possibly `Complete` if it's possible in implementation to determine whether it's completed etc.

**Comment by jd1378** [comment] 2018-02-12 13:14
@RedNesto in answer to your question , i think it depends on the implementation of the humanoid , while it can start digging  , there's actually little to no benefit in doing so imo , since the swing and interaction should be handled separately ?

**Comment by ryantheleach** [comment] 2018-02-12 14:36
@RedNesto Many entities in modded Minecraft can dig, not just humans.

**Comment by RedNesto** [comment] 2018-02-12 16:09
I only used humans as an example for vanilla. I also was in a hurry and haven't had the time to add reference to mods :3

**Comment by ImMorpheus** [comment] 2021-03-08 22:33
Fixed by https://github.com/SpongePowered/SpongeAPI/pull/2278

**Closed as completed by ImMorpheus** 2021-03-08 22:33 UTC
Labels: status: input wanted, system: event, type: enhancement
