### ISSUE TITLE
TextTemplate serializer problems

### ISSUE THREAD

**Issue by Wundero** [SpongePowered/SpongeAPI#1493] opened 2017-02-19 07:58 UTC
In the [TextTemplate serializer](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/text/serializer/TextTemplateConfigSerializer.java#L84-L86), three lines have problems that prevent it from properly deserializing.

The first two lines should, in the `getNode` call, have the nodes be prefixed with `NODE_OPTIONS`, because the serialization method does that and so there is a discontinuity between the two.

The third line should use `TOKEN_TEXT` rather than `TypeToken.of(Text.class)`, for the sake of consistency.

I would try to submit a PR for this but I do not have the proper setup at the moment, so if this is not changed when I get my computer properly setup I will do it.

**Comment by Lignium** [comment] 2019-06-12 20:15
The issue is still not fixed.

https://github.com/SpongePowered/SpongeAPI/blob/85a951a7c250110a19ece0276cf218bb1c9a1d05/src/main/java/org/spongepowered/api/text/serializer/TextTemplateConfigSerializer.java#L84-L85

https://github.com/SpongePowered/SpongeAPI/blob/85a951a7c250110a19ece0276cf218bb1c9a1d05/src/main/java/org/spongepowered/api/text/serializer/TextTemplateConfigSerializer.java#L94-L95

**Comment by ImMorpheus** [comment] 2020-08-23 20:38
As of API 8 we are now using [Adventure](https://github.com/KyoriPowered/adventure). 

This means the old Text api is gone and all the related issues (especially those involving breaking changes) are no longer relevant, therefore I'm closing this.

**Closed as completed by ImMorpheus** 2020-08-23 20:38 UTC
Labels: type: bug, system: text
