### ISSUE TITLE
Ability to Hide Entities - "Sending Single Client Data"

### ISSUE THREAD

**Issue by pokewillpower** [SpongePowered/SpongeAPI#2417] opened 2022-03-05 18:41 UTC
### Major SpongeAPI version

8

### Is this likely to be a breaking change?

I don't know

### What are you requesting?

Back in API 7 there was talk of implementing functionality that was in Bukkit's API to Sponge.
https://github.com/SpongePowered/SpongeAPI/issues/1614

I feel that continuing to neglect this functionality is severely limiting the capabilities that Sponge servers have in comparison to their Spigot counterparts. It would be fantastic if this issue could be brought back up for the current API as the ability to hide entities would allow for more Wynncraft MMO-type servers that utilize Sponge/SpongeForge.

Again referencing the previous issue, "Sponge does have Player only Block support with Player.sendBlockChange(Vector3i, BlockState);" and I would hope that implementing the aforementioned capability with that in mind should easily allow for
[ ] Player only Time 
[ ] Player only Weather 
[ ] Player only Entity

**Comment by gabizou** [comment] 2022-05-17 06:42
Closing as it's a duplicate of #1614... Why would you open a new issue to just reiterate what was requested *and linked*......

**Closed as completed by gabizou** 2022-05-17 06:42 UTC
Labels: status: needs triage
