### ISSUE TITLE
Add getAliases to CommandSpec

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeAPI#1788] opened 2018-02-26 23:35 UTC
Right now, we don't have a way to get the name or alias of an CommandSpec (correct me if I'm wrong), and that turns registering dynamic commands a bit tricky. It'd be nice if we had a `List<String> getAliases()` on CommandSpec (*or CommandCallable?*).

**Comment by SimonFlash** [comment] 2018-02-27 03:48
Neither `CommandSpec` nor `CommandCallable` store names or aliases, so I really don't know what you're trying to accomplish with this. You'd need to make multiple changes to `CommandSpec` and `CommandManager` if you wanted them to store that information (`CommandCallable` isn't going to change). This may not be breaking, but I don't think it's usefulness justifies the time spent to make these changes *especially* with the command refactor coming in API 8. Please clarify what you mean because at the moment I'm not understanding how you think this could be implemented.

**Comment by Eufranio** [comment] 2018-03-02 17:07
Let's say I have a command and a subcommand. I wanted to be able to populate pagination list with the usage of those commands, but `CommandSpec#getUsage` doesn't return the **name** of the command, only the rest. So, if I have a `/foo bar <arg>` command, `barSpec.getUsage()` would ONLY return `<arg>`. 

That way, I cannot properly get the usage of those commands. My wish was to get a clean way of displaying the whole `/foo bar <arg>` on a line. At the moment, I have to manually add the `/foo bar` to a list and then get the usage of the spec.

I see that `CommandMapping` has a `getPrimaryAlias` method, which is useful, but I seem to only be able to get a `CommandMapping` in the return of `CommandManager#register()`, when registering the main command spec. That way, I don't seem to be able to get the mapping of the subcommands, nor their name and usage.

**Comment by SimonFlash** [comment] 2018-03-02 18:42
>but `CommandSpec#getUsage` doesn't return the **name** of the command, only the rest.

Because a `CommandSpec` doesn't have a *concept* of a command having an alias. The `CommandSpec` only contains information relevant to the processing of that command, such as the arguments, and not the aliases it is registered under.

The limitation of `CommandMapping`s only knowing their own aliases is a limitation of how the system is structured and the [mis]use of the `ChildCommandElementExecutor`. I talked about this in #1714 when I did work with dynamic commands of my own, to no avail. You can see the resulting confusion [here](https://github.com/SimonFlash/CmdBuilder/blob/master/src/main/java/com/mcsimonflash/sponge/cmdbuilder/internal/Scripts.java) with an [overwrite mixin](https://github.com/SimonFlash/CmdBuilder/blob/master/src/main/java/com/mcsimonflash/sponge/cmdbuilder/mixin/MixinSpongeCommandManager.java) into `SpongeCommandManager` for tab completion.

> At the moment, I have to manually add the `/foo bar` to a list and then get the usage of the spec.

I agree, there isn't a clean solution to doing this using only a `CommandSpec` - see [this monstrosity](https://github.com/SimonFlash/TeslaCrate/blob/master/src/main/java/com/mcsimonflash/sponge/teslacrate/command/Base.java#L125-L177) in TeslaCrate as an example. I've since migrated this to use a custom [`Command`](https://github.com/SimonFlash/TeslaPowered/blob/master/TeslaLibs/src/main/java/com.mcsimonflash.sponge.teslalibs/command/Command.java) class in TeslaLibs that contains both a `CommandSpec` and a list of aliases, which you're free to make use of.

However, understand that what your asking for is a *rewrite of the Command API*. Before you could even look into having a `getAliases` method, the `CommandSpec` has to have aliases in the first place. This is not something that can be feasibly done in API 7, and it's being replaced in API 8 anyways.

**Comment by ryantheleach** [comment] 2018-03-03 14:02
I looked into this a while back whilst trying to create BetterHelp (Which was a long time ago) I remember hitting snags.

Anyway, the `Dispatcher` has a getCommands() function on it that allows you to get the mappings.

However ChildCommandExecutors don't readily expose their dispatchers.

Also note the CommandManager is a Dispatcher.

It would be relatively simple to expose the dispatcher of ChildCommandExecutors without much hassle IMO.

**Comment by dualspiral** [comment] 2018-03-03 14:38
While that's all correct, first thing to mention that the command spec, and its replacement, don't have knowledge of their registrations. This is by design - the separation of concerns add flexibility and simplicity to the implementation. The command manager only cares about "root" commands, subcommands are handled by the parent.

Not that this is ideal, but you can do what you want now somewhat dynamically if you own the commands you care about. As you indicate, you can store the `CommandMapping`, that gives you the primary alias.

> That way, I don't seem to be able to get the mapping of the subcommands, nor their name and usage.

As you are the sole owner of the subcommands, you know how they are registered and to what commands, which you can use the `CommandMapping` to verify the aliases.

As for the `ChildCommandElementExecutor`, yes, we _could_ expose the `Dispatcher`, but in this scenario, it doesn't achieve anything because the request is to get an alias from a spec, not a spec/mapping from an alias. What this issue is asking for is the ability to supply a `CommandCallable`/`Command` to the dispatcher and see what subcommands its registered under to do this, but if a plugin has this information, it either owns the command so knows the location, or it obtained the command from the tree, so it known the location.

**Comment by dualspiral** [comment] 2020-06-09 10:20
Can't be done for API 7, and API 8 rips up the current API anyway, so closing this.

**Closed as completed by dualspiral** 2020-06-09 10:20 UTC
Labels: system: command
