### ISSUE TITLE
Add Texts.substring()

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/SpongeAPI#801] opened 2015-08-11 14:33 UTC
Basically, I would like to have the equivalent of [`String.substring()`](http://docs.oracle.com/javase/7/docs/api/java/lang/String.html#substring(int,%20int)), but with Text. I think this would be useful for a couple things:

* (In my BLWarps plugin): Find all instances where the name of a warp is mentioned, then find the starting and ending indices of the warp name in the Text. Then, I would substring everything but the warp name and insert a clickable text prompting the user to warp.
* Anti-Profanity plugins: Same thing as above (eg. find curse words and replace them with asterisks)

This would be incredibly useful to have in the API and still have it retain formatting

**Comment by ST-DDT** [comment] 2015-08-11 16:32
> * (In my BLWarps plugin): Find all instances where the name of a warp is mentioned, then find the starting and ending indices of the warp name in the Text. Then, I would substring everything but the warp name and insert a clickable text prompting the user to warp.
* Anti-Profanity plugins: Same thing as above (eg. find curse words and replace them with asterisks)

This sound more like a `String.replace()` than substring.
You request actually consist of multiple requests:
* `indexOf` or `charAt` to determine the split points/word boundaries
* `substring`

However these methods seem to be better suited to do the job.
* `split`
* `replace`
* regex in general

IMO this methods are not needed since they only work on `Text.Literal`s that by their own nature are just wrapped strings. So you should better unwrap them do you cleanup/magic with it and then wrap it again. There are far to many useful String methods to recreate them all for Texts.

Here an example
````java
public Text wordChecker(Text text, Function<String,Text> wordFunction) {
    if (text instanceof Text.Literal) {
        return wordChecker(text, wordFunction);
    } else {
        return text; // Cannot do anything with that
    }
}

public Text wordChecker(Text.Literal text, Function<String,Text> wordFunction) {
    TextBuilder builder = TextBuilder.withFormating(text); // Helper method
    String content = text.getContent();
    String[] parts = content.split(" ");
    builder.append(wordFunction.apply(part))
    for (int i = 1; i < parts.length; i++) {
        builder.append(Texts.of(" "));
        builder.append(wordFunction.apply(part));
    }
    for (Text child : text.getChildren()) {
        builder.append(wordChecker(child, wordFunction));
    }
    return builder.build();
}
````
However the part with the word function is not flexible enough for an API method.
I actually though of using something like a  `TextProcessor` extends `Function<Text,Text>`
that can be used to apply that magic to each entry individually. But you would have to implement all yourself so adding it to the API is quite useless.

**Comment by JBYoshi** [comment] 2015-08-30 22:46
@RobertHerhold For the anti-profanity plugin, you'd be changing the chat event. The chat event stores a `String`, not a `Text`, as players can only type `String`s into chat.

Not sure how to do the BLWarps stuff though. `Text.replace` would be hard to implement unless you're using `Text.Literal`s.

**Comment by ST-DDT** [comment] 2015-08-31 07:35
@JBYoshi Are you sure?
[PlayerChatEvent](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/entity/player/PlayerChatEvent.java) or will this be changed during the event rework?

**Comment by JBYoshi** [comment] 2015-08-31 22:11
Well, the player should only be sending a `String`.

**Comment by ST-DDT** [comment] 2015-12-20 19:51
IMO this issue can be closed because of
* lack of activity
* the proposed features would only apply to single `Text.Literal`s and thus can easily be replaced with the corresponding String methods. 
* In addition to that "Clean Chat" plugins will have to verify the String content anyway or they cannot trace multi colored words at all.
* The methods will have to provide a huge flexibility to be of actual use and thus forced to be quite complex and will most likely will have to deal with children that are not Text.Literal and thus cannot be taken into account properly or will cause unexpected behaviour.

**Comment by Minecrell** [comment] 2015-12-26 12:17
I'm going to close this for now, mostly for the reasons @ST-DDT already mentioned.
Operations like `replace`, or `substring` are not easily implementable using the design of Minecraft's new JSON chat format which has a tree-like structure, and special Text types like `Score`, or `Selector` make things like that even more difficult.

I'm not going to say there will never be something for that in the API, but if it will, then probably only through an additional different representation of a Text instance, which doesn't have the added complexity of a tree-structure.

**Closed by Minecrell** 2015-12-26 12:17 UTC
Labels: input wanted, text
