### ISSUE TITLE
Event for left clicking in air

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeAPI#1161] opened 2016-03-28 20:23 UTC
As described [here](https://forums.spongepowered.org/t/leftclickevent-in-air/12047) I would like to have a left click in the air event. :smiley:

Thanks!
RandomByte

**Comment by kashike** [comment] 2016-03-28 20:35
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/480 and https://github.com/SpongePowered/SpongeAPI/issues/1054

**Comment by randombyte-developer** [comment] 2016-03-28 20:45
Thanks

@Zidane Hoping this is in work. 😀

**Comment by kashike** [comment] 2016-03-28 20:47
...this should be closed, it's a duplicate.

**Closed** 2016-03-28 20:53 UTC
