### ISSUE TITLE
Add Line of Sight

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeAPI#969] opened 2015-12-20 06:57 UTC
Bukkit had an ````hasLineOfSight ```` method on entities, similarly Forge has a ````canEntityBeSeen ```` method with equivalent behavior. This method is simply performs a ray cast to see if entity A can see entity B in the expressions ````A.canEntityBeSeen(B)````.

I propose we have a method ````A.hasViewOf(B, checkFacingDir)````, determining whether A can see B, internally ray casting while ignoring transparent blocks. In the case that checkFacingDir is set to true, vertical and horizontal rotation are also factored in.This will help with developing "hide and seek" plugins, as well as boss fights, where the player may need to hide from a boss.

**Comment by DDoS** [comment] 2015-12-20 15:39
Duplicate of https://github.com/SpongePowered/SpongeAPI/issues/797. Also not fully implementable without the player FOV and aspect ratio. Without these you can't do frustum culling which is how you actually determine visibility. The client doesn't send these. Rays limit to a "can't see your face" solution, which doesn't imply being fully hidden.

**Closed by DDoS** 2015-12-20 15:39 UTC
Labels: enhancement
