### ISSUE TITLE
Console Error or Warnings

### ISSUE THREAD

**Issue by jelaw21** [SpongePowered/SpongeAPI#1377] opened 2016-10-02 03:08 UTC
I am running the Forge 2092 and sponge for the same version. I have this console output. Any Ideas?

Sponge Unable to find InventoryPacketState handler for click window packet: CPacketClickWindow{windowId=4, slotId=-999, usedButton=4, actionNumber=12, clickedItem=null, mode=QUICK_CRAFT}
01.10 23:03:47 [Server] Sponge Unable to find InventoryPacketState handler for click window packet: CPacketClickWindow{windowId=4, slotId=-999, usedButton=4, actionNumber=7, clickedItem=null, mode=QUICK_CRAFT}
01.10 23:03:45 [Server] Sponge Unable to find InventoryPacketState handler for click window packet: CPacketClickWindow{windowId=4, slotId=-999, usedButton=4, actionNumber=2, clickedItem=null, mode=QUICK_CRAFT}

**Comment by Aaron1011** [comment] 2016-10-02 03:09
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/925. You can safely ignore these for now.

**Closed by Aaron1011** 2016-10-02 03:09 UTC
