### ISSUE TITLE
Allow regenerating a region

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/SpongeAPI#574] opened 2015-04-18 04:01 UTC
Revert it to how it would look if it had when the world generator is first run.

Preferably accept an arbitrary Extent (possibly a plugin-implemented proy), might have to be a Chunk tho since world generation code is rather complex.

**Comment by Azatik** [comment] 2015-04-18 10:58
1 - I used to be offered to the regeneration of the chunk. The answer was to Deamon5550: https://github.com/SpongePowered/SpongeAPI/issues/360

2 - There is a problem with regeneration. How are we going to deal with it?
![2014-12-29_18 33 14](https://cloud.githubusercontent.com/assets/10154956/7215157/6bcef84a-e5e3-11e4-816e-aef3518f2b3a.png)

**Comment by zml2008** [comment] 2015-04-18 16:16
The deleteChunk method is no longer present in World. Still needs review.

That problem happens when the world generator changes (between MC versions usually). On the same generator, the same random seed is used meaning that the same results are given.

**Comment by ST-DDT** [comment] 2015-04-18 16:37
No trees and things like that are generated randomly. And if you try to restore villages the neighbor chunks have to be used.

**Comment by zml2008** [comment] 2015-04-18 17:07
pseudo-randomly. same seed->same results

**Comment by Deamon5550** [comment] 2015-04-18 18:25
Yeah, so long as the world generator is not modified the chunk generation is deterministic.

Our options at this point is either a method to regenerate chunks, or one to delete them. Personally I'm in favour of the delete method as it can have uses beyond world regeneration like world trimming.

**Comment by progwml6** [comment] 2015-04-18 18:26
regeneration is vital in order to retroactively place things in the world that are needed for new plugins

**Comment by zml2008** [comment] 2015-04-18 18:48
My only concern with delete vs regen is that this has to work if there are players still in the chunk.

**Comment by progwml6** [comment] 2015-04-18 18:53
regen should work when players are still in the chunk

**Comment by Deamon5550** [comment] 2015-04-18 18:56
That's a good point, I guess there is no real harm in having both for the two operations eh?

**Comment by zml2008** [comment] 2015-04-18 18:58
your choice how to do it, I just need to be able to regenerate a portion of a chunk (well, a whole chunk works too) that still contains players.

**Comment by Deamon5550** [comment] 2015-12-01 19:15
While perfectly possible from an impl standpoint to re apply the generation steps to regenerate a chunk, the populators will currently not play nice with regenerating a single chunk as they populate a 16x16 area which is offset by 8 blocks by design. To allow regenerating a single chunk we're going to have to add parameters to the `Populator.populate(World,Random)` method specifying the area to populate.

For regeneration everything will be dandy as long as all the surrounding chunks already exist, if they don't or if we are deleting and regenerating later we have an issue of potentially creating an 8 block buffer where either we have not populated or have double populated. 

We can handle this somewhat by populating an 8x8 area instead of a 16x16 area with our populators, however this will not play nice at all with modded biome decorates as we have limited control over where they are populating and no control at all over what size area they are populating.

I'll do some more investigation once #734 is merged.

**Comment by XakepSDK** [comment] 2017-03-08 11:24
What about this?

**Comment by bloodmc** [comment] 2019-02-14 21:21
Chunk regeneration API support has been added in commit https://github.com/SpongePowered/SpongeAPI/commit/6632f971b9a3b04aa839ed28ce4839e02dc32b9b

**Closed by bloodmc** 2019-02-14 21:21 UTC
Labels: status: accepted, status: help wanted, system: world, type: enhancement
