### ISSUE TITLE
Missing CatalogedBy in cataloged interfaces

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/SpongeAPI#1878] opened 2018-07-27 09:32 UTC
Not all of cataloged interfaces have the CatalogedBy annotation. So it was conceived?
For example, the interface Key, or first on the list the Advancement.

**Comment by ryantheleach** [comment] 2018-07-27 10:10
@Cybermaxke @ST-DDT I know you guys are fairly familiar with the Catalog system, Can you help me resolve this if no one else does?

**Comment by Cybermaxke** [comment] 2018-07-27 13:53
Not being on `Key` is something that should be fixed. For `Advancement`s isn't one because they can be reloaded, removed, etc. so it's not possible to list them

**Comment by ST-DDT** [comment] 2018-07-27 18:26
I just scanned the API and these are all direct children of `CatalogType` without `@CatalogedBy`:

Class | Catalog | Comment
--- | --- | ---
org.spongepowered.api.advancement.Advancement |  | 
org.spongepowered.api.advancement.AdvancementTree |  | 
org.spongepowered.api.block.BlockState |  | Too many possibilities (IIRC >>100)
org.spongepowered.api.block.trait.BlockTrait |  | Subclasses cataloged
org.spongepowered.api.data.DataRegistration |  | I'm not sure why this is a catalog or where it is used
org.spongepowered.api.data.key.Key | Keys | Should be fixed

[All CatalogTypes](https://jd.spongepowered.org/7.0.0/org/spongepowered/api/CatalogType.html)

If we use the fact the elements can be altered/removed/reloaded as a reason to not make a it a catalogued class then we should also remove the catalog from `CraftingRecipe` (and probably others).

From [`@CatalogedBy`](https://jd.spongepowered.org/7.0.0/org/spongepowered/api/util/annotation/CatalogedBy.html)

> The values served by catalog classes must remain the same and valid at all times.
> The variables in catalog classes may link to null if the given value is no longer valid and no appropriate alternative can be found.[...]

(Well at least after initialization, so this might be a corner case)

**Comment by Cybermaxke** [comment] 2018-07-27 19:17
Yeah, recipes shouldn't be cataloged in 1.13. 
null` would never be the case when a catalog is missing, a dummy would be used instead (how the fields are initialized).

**Comment by ST-DDT** [comment] 2018-07-27 20:25
> Yeah, recipes shouldn't be cataloged in 1.13.

I agree, a better way to search for recipes would be nice though (Which is offtopic).

> `null` would never be the case when a catalog is missing, a dummy would be used instead (how the fields are initialized).

Well, but that is not what the API contract states (Which may need an update as well).

IMO the dummy solution is not good/better than null because you get something and you have no way of telling whether it is hazardous (explodes on first use) or not. But this is probably offtopic again.

**Comment by gabizou** [comment] 2018-07-29 17:04
Advancements aren't going to be catalogued as Cyber mentioned.

BlockStates are too numerous.

BlockTrait by itself is not a proper type, the subclasses are, which is why they are catalogued.

DataRegistration is as it's name lends itself, a registration for data, used by the implementation to link to deserializers and serializers for custom data to be stored onto entities etc.

Keys is the only one that realistically needs to be fixed.

> IMO the dummy solution is not good/better than null because you get something and you have no way of telling whether it is hazardous (explodes on first use) or not. But this is probably offtopic again.

Dummy was designed for ensuring that we weren't passing around nulls and IDE's would quit whining about "oh, you're using a null!" The methods are stubbed, but at the same time, it's the implementation's job to ensure that none of the dummy objects persist after startup, as the tests should be testing at some point soon.

But at the end of the day, it's purely documentation/accessory to assist developers understanding where to find some common vanilla found catalog types.

**Comment by Lignium** [comment] 2018-11-02 15:43
On the other hand, we can create our own keys for our data. In this case, a specific catalog of keys cannot be. Maybe the annotation is not needed?

**Comment by Cybermaxke** [comment] 2018-11-02 18:10
There are many other cases where you can create custom catalog types of which the default ones (vanilla) are put in a catalog and there can be plugin provided/modded ones. Since there is a catalog for `Key`s, we should link it with the annotation.

**Comment by Cybermaxke** [comment] 2019-01-27 18:18
Fixed in https://github.com/SpongePowered/SpongeAPI/commit/91a68f374d3f10ce2b8911a1ce0cde460c706ff8

**Closed as completed by Cybermaxke** 2019-01-27 18:18 UTC
Labels: system: registry
