### ISSUE TITLE
Add a class that represents ItemTypes with enchantments and other things

### ISSUE THREAD

**Issue by CrystalMageX** [SpongePowered/SpongeAPI#1092] opened 2016-02-22 05:12 UTC
One of the reasons issue #1074 was submitted was because `ItemStack`s were the only way to hold enchanted sign-shop items. The class `ItemStack` should only represent the **contents** of an *inventory slot*, and be *limited to max size* the particular item supports. I suggested that a `Map<ItemType, Integer>` be used, but that did not hold the required enchantments. This is why there should be a `ItemData` class in between `ItemStack` and `ItemType`, and **all of the `DataManipulator`s** of `ItemStack` be moved into it. `ItemStack` would be like a special kind of `Pair<ItemData, Integer>` that limits sizes, `ItemData` would be where all the `DataManipulator`s would be, and `ItemData` would represent all of the **items from vanilla / forge**.

**Comment by gabizou** [comment] 2016-02-22 16:37
I'm sure that the issue is already closely related to just being able to set the `ItemStack` quantity greater than the `ItemType`'s max defined stack size. Aside from that, there are things called `ItemStackSnapshot`s that can represent an `ItemStack` without being able to modify said snapshot. 

I have honestly no clue what function this `ItemData` would represent or how it would be used, let alone the fact that it's acting more as a cache of the possible `ItemStack`s, which to me is rather wasteful of resources.

**Comment by MichaelFedora** [comment] 2016-03-21 00:24
Then I suppose that for shop-signs, storing item data would best be done by using `ItemStackSnapshot`s. But then the other problem is, is there a way to (nicely) serialize `ItemStackSnapshot`s, and then deserialize them? This would be for storing them into a Database..

`ItemType`, I "serialize" by it's `getId`/`getName`.
Amount is by Integer.

...And I suppose you could then serialize `ItemEnchantment` by it's id & level, and then each lore by a (text)-string, durability, and so forth for every DataSerializable object is has with it...

Would be quite a bit of work, but it could be done, by the plugin author.

**Comment by gabizou** [comment] 2016-03-21 02:22
@MichaelFedora `ItemStackSnapshot`s are natively `DataSerializable`s, meaning they can be serialized to `DataContainer` and likewise translated into `ConfigurationNode`s, etc. The advantage is that with this system, you'd be able dump it as a blob of text for the full `ItemStackSnapshot` with all data related to it, including enchantments and custom plugin data.

Closing as there's no real disagreement with using the snapshots to do this very utility functionality.

**Closed by gabizou** 2016-03-21 02:22 UTC
Labels: data, input wanted
