### ISSUE TITLE
Get Highest Block at Specific Location

### ISSUE THREAD

**Issue by kmecpp** [SpongePowered/SpongeAPI#1375] opened 2016-10-01 17:44 UTC
In Bukkit there was a `World.getHighestBlockAt(Location)` and `World.getHighestBlockYAt(Location)` method, which returned the highest non air block at the given location and the Y position of that block respectively. 

Unless there is some other really easy way to do this, I think these methods should be added to API

**Comment by Maxqia** [comment] 2016-10-02 00:27
PS for any devs looking at this, Internally it is net.minecraft.world.getHeight(BlockPos)

**Comment by Zidane** [comment] 2016-10-02 00:55
@kmecpp 

Out of curiosity, what were these generally used for?

**Comment by ewized** [comment] 2016-10-02 02:08
I used them for optimizing things that needed to check for specific actions in blocks that may be intensive other wise.

**Comment by me4502** [comment] 2016-10-02 03:18
I used it in CraftBook for Bukkit in the Snow feature, to determine where the snow should form. It's basically a convenience method.

**Comment by ryantheleach** [comment] 2016-10-02 03:23
I would use them to check whether skylight is accessible for our old servers teleport system, it would "beam up" players as a balance check against people teleporting out of mineshafts.

It's also useful for working out where to teleport people to when given 2d co-ordinates.

**Comment by me4502** [comment] 2016-10-02 07:10
I'm not at a computer to check right now, but what does this do internally? Does it just iterate over the column?

It does make sense to mirror this if it does anything different like caching.

**Comment by Deamon5550** [comment] 2016-10-02 07:14
There is no caching it simply iterates.

**Comment by ST-DDT** [comment] 2016-10-02 07:36
> There is no caching it simply iterates.

Then there is no need to expose this.

Well there a too many too easy to implement features connected to this. 

* Highest block below height X,
* Also ignore leaves or grass
* ignore floating blocks
* ...

So it should be the plugins job to do this. If the plugin needs help it can use the block ray for help. Maybe we can add a helper method for column iterating there if necessary.

**Comment by Minecrell** [comment] 2016-10-02 08:25
`World.getHeight(BlockPos)` does not iterate, it returns the current value from an internal height map of the chunk.

**Comment by me4502** [comment] 2016-10-02 09:51
In that case, it makes sense to expose this.

**Comment by Deamon5550** [comment] 2016-10-02 21:56
@Minecrell that value is useless almost by the time that the populators run

**Comment by ryantheleach** [comment] 2016-10-03 13:53
Honestly most of the time getting the highest skylight block is what people want, they are just not thinking about it.

If the two methods were in and documented, it would make people think twice about choosing which one.

Additionally if you make people iterate themselves, you have the problem of cubic chunks, whilst Minecraft might not make any optimizations for highest block, cubic chunks would be able to skip any chunks not generated.

**Comment by theboomer** [comment] 2016-10-05 05:37
iterating thru a column is poorly inefficient compared to a binary greater-than-less-than search anyways - maximum of 8 guesses vs iterating up an average of 80 from base, or down an average of 170 from the top, etc :)   But at least this value is in the minecraft data as-is.

**Comment by Deamon5550** [comment] 2016-10-05 06:08
@theboomer except that you can't binary search for the height because you have no idea if the actual height is greater than or less than your current search position.

**Comment by theboomer** [comment] 2016-10-05 07:40
not as directly, but you can if looking for a location with some extreme value that then is different later.   If its got the value needed, its that height or lower; if its the compliment, its higher than that value.  You'd have to track the "sofar minimum and maximum" possibly, to know if you checked in the wrong direction and backstep the other way to envelope the point. So maybe max of 9 or 10 chops instead of 8 due to some extra some back-and-forth.  I did it a long time ago with one of the lighting properties myself as a challange, but lost that code
But again in this case, its info readily pulled from the internal chunk archetecture nbt, and not a concern.

**Comment by theboomer** [comment] 2016-10-05 12:58
Just for completeness sake: A quasi-binary quasi-recursive search for boundary blocks like this.  Find a way to describe a boundary in terms of a binary-test condition that transitions as it would iterating from one end or the other, and it can be found this way, 100% of the time in exactly 8 tests for 256 spaces.

http://image.prntscr.com/image/2ef726ba28c9450a8e0701df22e1c02c.png

**Comment by Barteks2x** [comment] 2016-10-05 14:50
There are actually 2 height values that may be useful, one of them is the one that ignores transparent blocks (including glass) and the other that is called precipitation heightmap which ignores non-solid blocks like tall grass or torches but doesn't ignore glass.

Both of them make sense in different situation.

**Comment by Maxqia** [comment] 2016-10-05 22:44
So getHightestLitBlock and getHighestBlock?

**Comment by JBYoshi** [comment] 2016-10-06 01:34
I'd say `getHighestOpaqueBlock` and `getHighestSolidBlock`, respectively.

**Comment by ryantheleach** [comment] 2016-10-06 01:51
@theboomer The problem is communication, I'm pretty sure most people are aware of what a binary search is.

Deamon's assumption was that people were looking for the true highest block, not the highest non-transparent block.

**Closed** 2017-04-18 03:10 UTC
Labels: system: world
