### ISSUE TITLE
TextTemplate not working correctly ?

### ISSUE THREAD

**Issue by Ewoutvans** [SpongePowered/SpongeAPI#1890] opened 2018-08-04 19:19 UTC
When using `TextTemplate` adding Color, String, Color, String isn't given the desired output when serialized or converted to Text.

Here are some examples:

`TextTemplate.of(TextColors.GRAY, "[", TextColors.RED, "MAIN", TextColors.GRAY, "] ")`

Output:
```
messages {
    main {
        arguments {}
        content {
            color=gray
            extra=[
                {
                    text="["
                },
                {
                    text=MAIN
                },
                {
                    text="] "
                }
            ]
            text=""
        }
        options {
            closeArg="}"
            openArg="{"
        }
    }
}
```

Wrapping it in a Text gives a different output but still not what we expect.

`TextTemplate.of(Text.of(TextColors.GRAY, "[", TextColors.RED, "MAIN", TextColors.GRAY, "] "))`

Output:
```
messages {
    main {
        arguments {}
        content {
            color=gray
            extra=[
                {
                    text=MAIN
                },
                {
                    text="] "
                }
            ]
            text="["
        }
        options {
            closeArg="}"
            openArg="{"
        }
    }
}
```

A solution is wrapping every Color, String in a Text.

`TextTemplate.of(Text.of(TextColors.GRAY, "["), Text.of(TextColors.RED, "MAIN"), Text.of(TextColors.GRAY, "] "))`

Output:
```
messages {
    main {
        arguments {}
        content {
            color=gray
            extra=[
                {
                    color=red
                    text=MAIN
                },
                {
                    color=gray
                    text="] "
                }
            ]
            text="["
        }
        options {
            closeArg="}"
            openArg="{"
        }
    }
}
```

Is this by design?

**Comment by ryantheleach** [comment] 2018-08-04 20:47
Text templates have numerous issues, but I think this is a direct duplicate of : https://github.com/SpongePowered/SpongeAPI/issues/1855

**Closed as completed by ryantheleach** 2018-08-04 20:47 UTC
