### ISSUE TITLE
Improve BlockRay API to add entities support

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/SpongeAPI#1290] opened 2016-07-01 06:41 UTC
Hi !
In the same idea that we have a BlockRay class it could be nice if we could have an EntityRay class to check for exemple at which entity a player is looking. Maybe a third class that support both Block and Entity would be nice too but it would be a bit complicated to do it properly.

**Comment by ryantheleach** [comment] 2016-07-01 08:49
It wouldn't be too complicated, we can potentially hook into the ray tracing that is already in the game.

**Comment by Yeregorix** [comment] 2016-07-01 09:39
Yes, this is what I was using in past, but on the side of the API, merging entity filters and block filters, entity results and block results can be complicated. The third class would be very heavy, except if a good API designer work on it. I was thinking that instead of using a third class, plugin devs can iterate over both BlockRay and EntityRay at same time and do what they want.

**Comment by DDoS** [comment] 2016-07-01 13:56
I'm working on this in feature/aabb. I'll add a hook into MC's ray tracing for combined entities and blocks.

**Comment by DDoS** [comment] 2016-07-01 15:14
Duplicate of: https://github.com/SpongePowered/SpongeAPI/issues/797

**Closed by DDoS** 2016-07-01 15:14 UTC
Labels: duplicate
