### ISSUE TITLE
Fire interact with air event on C0APacketAnimation

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#1054] opened 2016-01-26 20:45 UTC
There is no "interact with air" event fired in `C0APacketAnimation`.

**Comment by ThornsOfire** [comment] 2016-01-30 08:27
!!!!

**Comment by Aaron1011** [comment] 2016-02-26 02:24
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/480

**Closed by Aaron1011** 2016-02-26 02:24 UTC
