### ISSUE TITLE
Redundant serialized data of Location

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/SpongeAPI#1914] opened 2018-09-23 10:15 UTC
As it was already noted earlier at Discord, a world name and a block type is redundant data. Furthermore the block type may not be coincide with a block type which located in the world...

Source code:
```
World world = Sponge.getServer().getWorlds().iterator().next();
Location<World> location = world.getLocation(0, 0, 0);
        
System.out.println(DataFormats.JSON.write(location.toContainer())));
```

Result (formatted):
```
{
    "ContentVersion": 1,
    "WorldName": "world",
    "WorldUuid": "63f28a76-c4a8-4d10-b5f5-747ba8304506",
    "BlockType": "minecraft:bedrock",
    "X": 0.0,
    "Y": 0.0,
    "Z": 0.0
}
```

**Comment by ImMorpheus** [comment] 2018-09-23 11:32
BlockType is a duplicate of https://github.com/SpongePowered/SpongeCommon/issues/1720

**Comment by Lignium** [comment] 2018-09-23 11:47
Will there be any decision on this issue? It's not right to manually write down UUID of world and coordinates (Vector3i) to configuration.

**Comment by gabizou** [comment] 2018-09-25 04:56
~move to common

**Comment by limbo-app** [comment] 2018-09-25 04:56
Hey @Lignium! I've moved your issue to [SpongePowered/SpongeCommon#2109](https://github.com/SpongePowered/SpongeCommon/issues/2109).

**Closed as completed** 2018-09-25 04:56 UTC
Labels: system: data, resolution: moved
